services:
  backend:
    build:
      context: ./Proyecto_TiendaNC
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    ports:
      - "8080:8080"
    container_name: backend
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
    depends_on:
      - database 
    networks:
      - tienda-red

  frontend:
    build:
      context: ./Proyecto_TiendaNC_interfaz
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    container_name: frontend
    environment:
      - TZ=America/Mexico_City
    depends_on:
      - backend
    networks:
      - tienda-red

  database: 
    image: postgres:13
    environment:
      POSTGRES_DB: dulcesnc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: America/Mexico_City
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    container_name: Dulceria-DB
    ports:
      - "5432:5432" 
    networks:
      - tienda-red

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiNzhmZTUxOGI2OGVlODZjZmJjYjdjMTI2NzY1N2Q2MmIiLCJ0IjoiNWYzNGQwNjYtZDE4NC00NzhhLTk4ZDItYjliMzJkY2M3ZDljIiwicyI6Ik1tWmpOV0kwWXpZdFpHRXpNeTAwTkRBeExXSTNaVFl0WVRCbU9ETTNZbVk1TXpWaSJ9
    networks:
      - tienda-red
    depends_on:
      - frontend

networks:
  tienda-red:
    driver: bridge

volumes:
  db-data: